package com.tour_it.producer.enums

enum class Navigation {
    AUTHENTICATION,
    SIGN_IN,
    SIGN_UP,
    HOME,
    HOMEPAGE,
    SPLASH,
    SPLASH_SCREEN,
    MAP,
    MAP_SCREEN,
    POINTS,
    POINTS_SCREEN,
    SEARCH,
    SEARCH_SCREEN,
    CART,
    CART_SCREEN,
    PRODUCT,
    PRODUCT_SCREEN_HOTEL,
    PRODUCT_SCREEN_EVENT,
    PRODUCT_SCREEN_RESTAURANT,
    PROFILE,
    PROFILE_SCREEN
}